#!/usr/bin/env bash
set -Eeo pipefail

MIGRATIONS_DIR=$(dirname $(dirname $0))
. "${MIGRATIONS_DIR}/common"

make_directories(){
  mkdir -p plabsdb
  sudo chmod -R 777 plabsdb

  mkdir -p plabs/data
  sudo chmod -R 777 plabs
}

install_config(){
  # update the docker-compose file and restart to take the changes
  mydir=$(dirname $0)
  customize_docker_compose_file "${mydir}/docker-compose-after.yml"
  cp "${mydir}/docker-compose-after.yml" "${PL_ROOT_DIR}/docker-compose.yml"
  cp "${mydir}/nginx.conf" "${PL_ROOT_DIR}/nginx.conf"
}

main(){
  # we can skip 001 and 002
  make_directories
  install_config

  # All of the Keycloak init has to happen
  "${MIGRATIONS_DIR}/000003_init_kc/up"
}

[ "${BASH_SOURCE[0]}" != "${0}" ] ||
  main
