apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: flower
  name: flower
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 5555
  selector:
    io.kompose.service: flower
