apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: pg-db
  name: pg-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  {{- with .Values.rwo_storage_class }}
  storageClassName: {{ . }}
  {{- end }}
  volumeMode: Filesystem
