FROM registry.access.redhat.com/ubi8/python-38

USER 0
WORKDIR /app

COPY requirements.txt /app/

RUN pip install --upgrade pip && \
    pip install -r requirements.txt && \
    rm requirements.txt

USER 1001
