trigger:
- master
- dev
- stage


### TEST UBUNTU ###

jobs:
  - job: test_ubuntu
    pool:
        vmImage: "ubuntu-16.04"
    steps:
    - bash: |
        cd scripts
        CONDA_ENV_FILE="../backend/environment.yml"
        echo "Test in Ubuntu"


### TEST WINDOWS  ###

  - job: test_windows
    pool:
        #win-pool
        vmImage: "windows-latest"
    steps:
    - powershell: |
        Write-Host "test in windows"  


### TEST OSX  ###

  - job: test_osx
    pool:
        vmImage: "macOS-10.14"
    steps:
    - bash: |
        echo "Test in osx" 


### BUILD UBUNTU ###

  - job: build_ubuntu
    dependsOn:
        ["test_ubuntu", "test_windows", "test_osx"]
    pool:
        vmImage: "ubuntu-16.04"
    steps:
    - bash: |
        cd scripts/
        ./setup_ubuntu.sh
      displayName: 'Environment setup'
    
    - bash: |
        cd scripts/
        bash -i build_ubuntu.sh
      displayName: 'Build'
    
    - publish: $(Build.Repository.LocalPath)/build/frontend_out/
      artifact: images_ubuntu


### BUILD WINDOWS ###

  - job: build_windows
    dependsOn:
        ["test_ubuntu", "test_windows", "test_osx"]
    pool:
        #win-pool
        vmImage: "windows-latest"
    steps:
    - script: |
        cd scripts/
        ./setup_windows.bat
      displayName: 'Environment setup'

    - script: |
        cd scripts/
        ./build_windows.bat
      displayName: 'Build'
    
    - publish: $(Build.Repository.LocalPath)/build/frontend_out/
      artifact: images_windows


### BUILD OSX ###

  - job: build_osx
    dependsOn:
        ["test_ubuntu", "test_windows", "test_osx"]
    pool:
        vmImage: "macOS-10.14"
    steps:
    - bash: |
        cd scripts/
        ./setup_osx.sh
      displayName: 'Environment setup'

    - bash: |
        cd scripts/
        bash -i build_osx.sh
      displayName: 'Build'
    
    - publish: $(Build.Repository.LocalPath)/build/frontend_out/
      artifact: images_osx


### PUBLISH SCRIPTS (for deployment purposes)

  - job: publish_scripts
    pool:
        vmImage: "ubuntu-16.04"
    dependsOn:
      ["build_ubuntu", "build_windows", "build_osx"]
    steps:
      - publish: $(Build.Repository.LocalPath)/scripts/
        artifact: scripts

