trigger:
- none

variables:
  # CommitId is passed in to the app_variables.json file
  BuildVariables.CommitId : $(Build.SourceVersion)

jobs:
  - job: dockerbuild
    strategy:
      matrix:
        kernel:
          target: kernel
          repository: kernel
        frontend:
          target: frontend
          repository: frontend
        rygg:
          target: rygg
          repository: rygg
    pool:
      vmImage: 'ubuntu-16.04'

    steps:
    - checkout: self
      clean: true
      submodules: recursive
      persistCredentials: true

    - task: FileTransform@2
      inputs:
        folderPath: '$(System.DefaultWorkingDirectory)/'
        xmlTransformationRules: 
        jsonTargetFiles: '**/app_variables.json'

    - task: UsePythonVersion@0
      inputs: 
        versionSpec: '3.6'
        architecture: 'x64'
        addToPath: true

    - bash: |
        cd scripts/
        python build.py docker $(target)
      displayName: 'Assemble'

    - task: Docker@2
      inputs:
        containerRegistry: 'perceptilabs'
        repository: $(repository)
        command: 'buildAndPush'
        Dockerfile: 'build/docker/$(target)/Dockerfile'

