trigger:
- none

jobs:
  - job: startvm
    displayName: Start Worker
    steps:
    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'aws'
        regionName: 'us-east-2'
        scriptType: 'inline'
        inlineScript: 'aws ec2 start-instances --instance-ids i-02d83a036ea61ccd1 --region us-east-2'
        failOnStandardError: true

  - job: dockerbuild
    dependsOn: startvm
    pool: Docker Build

    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'perceptilabs'
        repository: '$(repository)'
        command: 'system'
        arguments: 'prune --force --all'
        addPipelineData: false
        addBaseImageData: false

  - job: stopvm
    dependsOn: dockerbuild
    displayName: Stop the build machine
    steps:
    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'aws'
        regionName: 'us-east-2'
        scriptType: 'inline'
        inlineScript: 'aws ec2 stop-instances --instance-ids i-02d83a036ea61ccd1 --region us-east-2'
        failOnStandardError: true
