trigger:
- none
#  - master
#  - stage

variables:
  BuildVariables.CommitId : $(Build.SourceVersion)

jobs:
### BUILD UBUNTU ###
  - job: build_ubuntu_py36
    pool:
        vmImage: "ubuntu-16.04"
    steps:

    - checkout: self
      clean: true
      submodules: recursive
      persistCredentials: true

    - task: FileTransform@2
      inputs:
        folderPath: '$(System.DefaultWorkingDirectory)/'
        xmlTransformationRules:
        jsonTargetFiles: '**/app_variables.json'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
        addToPath: true

    - bash: |
        cd scripts/
        bash -i build_posix.bash wheel
      displayName: 'Build'

    - publish: $(Build.Repository.LocalPath)/build/out/
      artifact: linux_3.6_wheel


  - job: build_ubuntu_py37
    pool:
        vmImage: "ubuntu-16.04"
    steps:
    - checkout: self
      clean: true
      submodules: recursive
      persistCredentials: true

    - task: FileTransform@2
      inputs:
        folderPath: '$(System.DefaultWorkingDirectory)/'
        xmlTransformationRules:
        jsonTargetFiles: '**/app_variables.json'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'
        addToPath: true

    - bash: |
        cd scripts/
        bash -i build_posix.bash wheel
      displayName: 'Build'

    - publish: $(Build.Repository.LocalPath)/build/out/
      artifact: linux_3.7_wheel


# ### BUILD WINDOWS ###
  #
  # - job: build_windows_py36
  #   pool:
  #       vmImage: "vs2017-win2016"
  #   variables:
  #     - group: Windows-build
  #   steps:
  #   - task: FileTransform@2
  #     inputs:
  #       folderPath: '$(System.DefaultWorkingDirectory)/'
  #       xmlTransformationRules:
  #       jsonTargetFiles: '**/app_variables.json'
  #
  #   - task: UsePythonVersion@0
  #     inputs:
  #       versionSpec: '3.6'
  #       architecture: 'x64'
  #       addToPath: true
  #
  #   - script: |
  #       cd scripts/
  #       ./setup_windows.bat
  #     displayName: 'Environment setup'
  #
  #   - script: |
  #       cd scripts/
  #       ./build_windows_wheel.bat
  #     displayName: 'Build'
  #
  #   - publish: $(Build.Repository.LocalPath)/build/out/
  #     artifact: windows_3.6_wheel
  #
  #
  # - job: build_windows_py37
  #   pool:
  #       vmImage: "vs2017-win2016"
  #   variables:
  #   - group: Windows-build
  #   steps:
  #   - task: FileTransform@2
  #     inputs:
  #       folderPath: '$(System.DefaultWorkingDirectory)/'
  #       xmlTransformationRules:
  #       jsonTargetFiles: '**/app_variables.json'
  #
  #   - task: UsePythonVersion@0
  #     inputs:
  #       versionSpec: '3.7'
  #       architecture: 'x64'
  #       addToPath: true
  #
  #   - script: |
  #       cd scripts/
  #       ./setup_windows.bat
  #     displayName: 'Environment setup'
  #
  #   - script: |
  #       cd scripts/
  #       ./build_windows_wheel.bat
  #     displayName: 'Build'
  #
  #   - publish: $(Build.Repository.LocalPath)/build/out/
  #     artifact: windows_3.7_wheel



### BUILD OSX ###
  - job: build_osx_py36
    pool:
        vmImage: "macOS-10.14"
    variables:
      - group: OSX-build
    steps:
    - checkout: self
      clean: true
      submodules: recursive
      persistCredentials: true

    - task: FileTransform@2
      inputs:
        folderPath: '$(System.DefaultWorkingDirectory)/'
        xmlTransformationRules:
        jsonTargetFiles: '**/app_variables.json'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
        addToPath: true

    - bash: |
        cd scripts/
        chmod 755 build_posix.bash
        ./build_posix.bash wheel
      displayName: 'Build'

    - publish: $(Build.Repository.LocalPath)/build/out/
      artifact: osx_3.6_wheel


  - job: build_osx_py37
    pool:
        vmImage: "macOS-10.14"
    variables:
    - group: OSX-build
    steps:
    - checkout: self
      clean: true
      submodules: recursive
      persistCredentials: true

    - task: FileTransform@2
      inputs:
        folderPath: '$(System.DefaultWorkingDirectory)/'
        xmlTransformationRules:
        jsonTargetFiles: '**/app_variables.json'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'
        addToPath: true

    - bash: |
        cd scripts/
        chmod 755 build_posix.bash
        ./build_posix.bash wheel
      displayName: 'Build'

    - publish: $(Build.Repository.LocalPath)/build/out/
      artifact: osx_3.7_wheel
