trigger:
- none

variables:
  BUILD_REASON: $(Build.Reason)
  BuildVariables.CommitId : $(Build.SourceVersion)
  BUILD_NUM: $(Build.BuildNumber)
  PYPI_REPO: pypi

jobs:
  - job: buildwheel

    strategy:
      matrix:
        linux_py3.6:
          artifact: linux_3.6_wheel
          image: 'ubuntu-latest'
          pyver: '3.6'
        linux_py3.7:
          artifact: linux_3.7_wheel
          image: 'ubuntu-latest'
          pyver: '3.7'
        osx_py3.6:
          artifact: osx_3.6_wheel
          image: 'macOS-10.14'
          pyver: '3.6'
        osx_py3.7:
          artifact: osx_3.7_wheel
          image: 'macOS-10.14'
          pyver: '3.7'
        win_py3.6:
          artifact: windows_3.6_wheel
          image: "vs2017-win2016"
          pyver: '3.6'
        win_py3.7:
          artifact: windows_3.7_wheel
          image: "vs2017-win2016"
          pyver: '3.7'

    pool:
        vmImage: $(image)

    steps:
    - script: |
        echo Setting PACKAGE_NAME_OVERRIDE to pl_nightly
        echo "##vso[task.setvariable variable=PACKAGE_NAME_OVERRIDE;]pl_nightly"

        echo Setting VERSION_EXTENSION to $(BUILD_NUM)
        echo "##vso[task.setvariable variable=VERSION_EXTENSION;]$(BUILD_NUM)"
      condition: or(
                  eq(variables['Build.Reason'], 'Schedule'),
                  eq(variables['FORCE_NIGHTLY'], 'true'))

    - script: |
        echo Package name is now $(PACKAGE_NAME_OVERRIDE)

    - checkout: self
      clean: true
      submodules: recursive
      persistCredentials: true

    - task: NodeTool@0
      inputs:
        versionSpec: '>=14.x'

    - task: FileTransform@2
      inputs:
        folderPath: '$(System.DefaultWorkingDirectory)/'
        xmlTransformationRules:
        jsonTargetFiles: '**/app_variables.json'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(pyver)
        architecture: 'x64'
        addToPath: true

    - bash: |
        cd scripts/
        python build.py wheel
      displayName: 'Build'

    - publish: $(Build.Repository.LocalPath)/build/out/
      artifact: $(artifact)

  - job: pushwheel
    dependsOn:
      - buildwheel
    condition: and(
                succeeded(),
                or(
                  eq(variables['FORCE_PUBLISH'], 'true'),
                  eq(variables['Build.Reason'], 'Schedule')))
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true
          architecture: 'x64'

      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          itemPattern: '**/*.whl'
          targetPath: '$(Pipeline.Workspace)'

      - script: |
          ls -al
          mkdir topush
          mv **/*.whl topush
          cd topush
          rename 's/linux_x86_64/manylinux1_x86_64/' *.whl
          # TODO: remove 2>/dev/null from the next line when issues with new pip are resolved.
          # It gives this warning:
          #     WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
          #     distutils: /opt/hostedtoolcache/Python/3.9.4/x64/include/python3.9/UNKNOWN
          #     sysconfig: /opt/hostedtoolcache/Python/3.9.4/x64/include/python3.9
          pip install --upgrade pip 2>/dev/null
          # TODO: remove 2>/dev/null from the next line when issues with new pip are resolved.
          pip install twine 2>/dev/null
          python -m twine upload --non-interactive -u __token__ --repository ${PYPI_REPO} *
        env:
          TWINE_PASSWORD: $(TWINE_PASSWORD_SECRET)
        workingDirectory: '$(Pipeline.Workspace)'
        displayName: Gather And Push Artifacts to PyPI
        failOnStderr: true

