trigger:
- none

jobs:
- job: checkincludedfiles
  displayName: Check included_files.txt
  steps:
  - task: Bash@3
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/scripts/check_included_files'
      arguments: '$(System.DefaultWorkingDirectory)/backend'
      failOnStderr: true
  - task: Bash@3
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/scripts/check_included_files'
      arguments: '$(System.DefaultWorkingDirectory)/fileserver'
      failOnStderr: true

- job: testpython
  displayName: Test python
  dependsOn: checkincludedfiles
  strategy:
    matrix:
      linux_py3.6:
        artifact: linux_3.6_wheel
        image: 'ubuntu-latest'
        pyver: '3.6'
      osx_py3.6:
        artifact: osx_3.6_wheel
        image: 'macOS-10.14'
        pyver: '3.6'
      win_py3.6:
        artifact: windows_3.6_wheel
        image: "vs2017-win2016"
        pyver: '3.6'

  pool:
    vmImage: $(image)

  steps:
  - checkout: self
    clean: true
    submodules: recursive
    persistCredentials: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(pyver)
      architecture: 'x64'
      addToPath: true

  - bash: |
      cd scripts/
      python build.py test
    displayName: 'Python tests'

- job: testfrontend
  displayName: Test frontend
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '>=14.x'
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: 'frontend'
  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: 'frontend'
      customCommand: 'run test:unit'
