trigger:
- none

jobs:
- job: test
  strategy:
    matrix:
      linux_py3.6:
        artifact: linux_3.6_wheel
        image: 'ubuntu-16.04'
        pyver: '3.6'
      osx_py3.6:
        artifact: osx_3.6_wheel
        image: 'macOS-10.14'
        pyver: '3.6'
      win_py3.6:
        artifact: windows_3.6_wheel
        image: "vs2017-win2016"
        pyver: '3.6'

  pool:
    vmImage: $(image)

  steps:
  - checkout: self
    clean: true
    submodules: recursive
    persistCredentials: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(pyver)
      architecture: 'x64'
      addToPath: true

  - bash: |
      cd scripts/
      python build.py test
    displayName: 'Python tests'

