trigger:
- none

resources:
  containers:
    - container: redis
      image: redis
      ports:
        - 6379

jobs:
- job: checkincludedfiles
  displayName: Check included_files.txt
  steps:
  - task: Bash@3
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/scripts/check_included_files'
      arguments: '$(System.DefaultWorkingDirectory)/backend'
      failOnStderr: true
  - task: Bash@3
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/scripts/check_included_files'
      arguments: '$(System.DefaultWorkingDirectory)/rygg'
      failOnStderr: true

- job: testpython
  displayName: Test python
  dependsOn: checkincludedfiles
  strategy:
    matrix:
      linux_py3.8:
        artifact: linux_3.8_wheel
        image: 'ubuntu-latest'
        pyver: '3.8'
      osx_py3.8:
        artifact: osx_3.8_wheel
        image: 'macOS-10.14'
        pyver: '3.8'
      win_py3.8:
        artifact: windows_3.8_wheel
        image: "vs2017-win2016"
        pyver: '3.8'

  pool:
    vmImage: $(image)
  
  services:
    redis: redis

  steps:
  - checkout: self
    clean: true
    submodules: recursive
    persistCredentials: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(pyver)
      architecture: 'x64'
      addToPath: true

  - bash: |
      export PL_REDIS_URL="redis://redis:6379"
      cd scripts/
      python build.py test
    displayName: 'Python tests'

- job: testfrontend
  displayName: Test frontend
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '>=14.x'
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: 'frontend'
  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: 'frontend'
      customCommand: 'run test:unit'
