trigger:
- dev

jobs:
### TEST UBUNTU ###

 - job: test_ubuntu
   pool:
       vmImage: "ubuntu-16.04"
   steps:
   - bash: |
       echo "Test in Ubuntu"


### TEST WINDOWS  ###

 - job: test_windows
   pool:
       #win-pool
       vmImage: "vs2017-win2016"
   steps:
   - powershell: |
       Write-Host "test in windows"  


### TEST OSX  ###

 - job: test_osx
   pool:
       vmImage: "macOS-10.14"
   steps:
   - bash: |
       echo "Test in osx" 


