trigger:
- none

jobs:
### TEST UBUNTU ###

 - job: test_ubuntu
   pool:
       vmImage: "ubuntu-16.04"
   steps:
    - checkout: self
      clean: true
      submodules: recursive
      persistCredentials: true

    - task: UsePythonVersion@0
      inputs: 
        versionSpec: '3.6'
        architecture: 'x64'
        addToPath: true

    - bash: |
        cd scripts/
        bash -i build_posix.bash test
      displayName: 'Python tests'

# ### TEST WINDOWS  ###
#
#  - job: test_windows
#    pool:
#        vmImage: "vs2017-win2016"
#    steps:
#     - checkout: self
#       clean: true
#       submodules: recursive
#       persistCredentials: true
#
#     - task: UsePythonVersion@0
#       inputs: 
#         versionSpec: '3.6'
#         architecture: 'x64'
#         addToPath: true
#
#     - script: |
#         cd scripts/
#         ./tests_setup_windows.bat
#       displayName: 'Environment setup'
#
#     - script: |
#         cd scripts/
#         ./test_windows.bat
#       displayName: 'Python tests'

### TEST OSX  ###

 - job: test_osx
   pool:
       vmImage: "macOS-10.14"
   steps:
    - checkout: self
      clean: true
      submodules: recursive
      persistCredentials: true

    - task: UsePythonVersion@0
      inputs: 
        versionSpec: '3.6'
        architecture: 'x64'
        addToPath: true

    - bash: |
        cd scripts/
        chmod 755 build_posix.bash
        ./build_posix.bash test
      displayName: 'Python tests'
