trigger:
- dev

jobs:
### TEST UBUNTU ###

 - job: test_ubuntu
   pool:
       vmImage: "ubuntu-16.04"
   steps:
    - bash: |
        cd scripts/
        bash -i test_ubuntu.sh


### TEST WINDOWS  ###

 - job: test_windows
   pool:
       #win-pool
       vmImage: "vs2017-win2016"
   steps:
    - script: |
          cd scripts/
          ./test_windows.bat


### TEST OSX  ###

 - job: test_osx
   pool:
       vmImage: "macOS-10.14"
   steps:
    - bash: |
        cd scripts/
        bash -i test_osx.sh


