trigger:
- dev

jobs:
### TEST UBUNTU ###

 - job: test_ubuntu
   pool:
       vmImage: "ubuntu-16.04"
   steps:
    - task: UsePythonVersion@0
      inputs: 
        versionSpec: '3.6'
        architecture: 'x64'
        addToPath: true
    - bash: |
        cd scripts/
        bash -i tests_setup_ubuntu.sh
      displayName: 'Environment setup'

    - bash: |
        cd scripts/
        bash -i test_ubuntu.sh
      displayName: 'Python tests'



### TEST WINDOWS  ###

 - job: test_windows
   pool:
       vmImage: "vs2017-win2016"
   steps:
    - script: |
        cd scripts/
        ./tests_setup_windows.bat
      displayName: 'Environment setup'

    - script: |
        cd scripts/
        ./test_windows.bat
      displayName: 'Python tests'


### TEST OSX  ###

 - job: test_osx
   pool:
       vmImage: "macOS-10.14"
   steps:
    - bash: |
        cd scripts/
        bash -i tests_setup_osx.sh
      displayName: 'Environment setup'

    - bash: |
        cd scripts/
        bash -i test_osx.sh
      displayName: 'Python tests'