trigger:
- none

resources:
  containers:
    - container: redis
      image: redis
      ports:
        - 6379:6379

services:
  redis: redis

jobs:
- job: checkincludedfiles
  displayName: Check included_files.txt
  steps:
  - task: Bash@3
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/scripts/check_included_files'
      arguments: '$(System.DefaultWorkingDirectory)/backend'
      failOnStderr: true
  - task: Bash@3
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/scripts/check_included_files'
      arguments: '$(System.DefaultWorkingDirectory)/rygg'
      failOnStderr: true

- job: testpython_linux
  displayName: Test python on linux
  dependsOn: checkincludedfiles

  pool:
    vmImage: ubuntu-latest
  
  services:
    redis: redis

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      architecture: 'x64'
      addToPath: true

  - bash: |
      cd scripts/
      python build.py test
    displayName: 'Python tests'

- job: testpython
  displayName: Test python
  dependsOn: checkincludedfiles
  strategy:
    matrix:
      osx_py3.8:
        image: 'macOS-latest'
        pyver: '3.8'
      win_py3.8:
        image: "windows-latest"
        pyver: '3.8'

  pool:
    vmImage: $(image)

  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(pyver)
      architecture: 'x64'
      addToPath: true

  - bash: |
      cd scripts/
      python build.py test
    displayName: 'Python tests'

- job: testfrontend
  displayName: Test frontend
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '>=14.x'
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: 'frontend'
  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: 'frontend'
      customCommand: 'run test:unit'
