apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: keycloak
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.keycloak.docker_image }}"
          imagePullPolicy: {{ .Values.keycloak.pull_policy | default "IfNotPresent" | quote }}
          env:
            - name: DB_ADDR
              value: {{ .Values.db_host | quote }}
            - name: DB_DATABASE
              value: {{ .Values.keycloak_db_name | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.db_pass | quote }}
            - name: DB_USER
              value: {{ .Values.db_user | quote }}
            - name: DB_VENDOR
              value: {{ .Values.db_vendor | quote }}
            - name: KEYCLOAK_LOGLEVEL
              value: INFO
            - name: ROOT_LOGLEVEL
              value: INFO
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - curl http://localhost:8080/auth/realms/master
            failureThreshold: 10
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          name: keycloak
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: {}
      restartPolicy: Always
