kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: perceptilabs
  labels:
    app.kubernetes.io/managed-by: Helm
    io.kompose.service: nginx
spec:
  # TODO: parameterize the namespace
  host: "{{ .Release.Name }}-{{ .Release.Namespace }}.{{ .Values.root_host }}"
  to:
    kind: Service
    name: nginx
    weight: 100
  port:
    targetPort: '80'
  wildcardPolicy: None
