apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: training-worker
  name: training-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: training-worker
    spec:
      {{- with .Values.imageCredentials.name }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      initContainers:
        - name: make-data-dir
          image: {{ .Values.bash_host.image | quote }}
          command: ['mkdir', '-p', '/plabs/data']
          volumeMounts:
            - name: plabs
              mountPath: /plabs
          imagePullPolicy: {{ .Values.bash_host.pull_policy | default "IfNotPresent" | quote }}
      containers:
        - name: training
          {{- if .Values.training.docker_image_override }}
          image: {{ .Values.training.docker_image_override | quote }}
          {{- else }}
          image: "{{ .Values.training.docker_repo }}:{{ .Values.pl_docker_tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.training.pull_policy | default "IfNotPresent" | quote }}
          args:
            - python
            - -m
            - celery
            - -A
            - perceptilabs.tasks.celery_executor
            - worker
            - --hostname=training
            - --queues=training
            - --pool=threads
          env:
            - name: container
              value: a
            - name: HOME
              value: /perceptilabs
            - name: PL_REDIS_URL
              value: redis://{{ .Values.redis_host }}
            - name: PL_RENDER_LOG_LEVEL
              value: {{ .Values.log_level }}
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /perceptilabs/Documents/Perceptilabs
              name: plabs
      restartPolicy: Always
      volumes:
        - name: plabs
          persistentVolumeClaim:
            claimName: plabs
