version: '3.4'

services:
  db:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - ${PL_ROOT_DIR}/plabsdb:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: rygg
      POSTGRES_USER: rygg
      POSTGRES_PASSWORD: rygg
    networks:
      - perceptilabs

  keycloak:
    image: quay.io/keycloak/keycloak:13.0.0
    restart: unless-stopped
    volumes:
       - ${PL_ROOT_DIR}/login_theme:/opt/jboss/keycloak/themes/perceptilabs
    environment:
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: rygg
      DB_PASSWORD: rygg
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
    depends_on:
      - db
    networks:
      - perceptilabs

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ${PL_ROOT_DIR}/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - keycloak
    networks:
      - perceptilabs

networks:
  perceptilabs:
    name: perceptilabs
