#!/usr/bin/env bash
set -Eeuo pipefail

expected=$(mktemp)
present=$(mktemp)
exceptions=$(mktemp)
cat included_files_exceptions.txt | sort > "${exceptions}"
cat included_files.txt | grep -v "^#" | grep -v "^$" | grep -v "tutorial_data" | sort > "${expected}"
git ls-tree --name-only -r HEAD | grep "^perceptilabs/" | grep -v "tutorial_data" | grep -v "test" | sort > "${present}"

rc=0
extra_files=$(join -v 1 "${present}" "${expected}" | join -v 2 "${exceptions}" -)
if echo "${extra_files}" | grep -q .; then
  echo "================================="
  echo "Extra files:"
  echo "${extra_files}"
  rc=1
fi

missing_files=$(join -v 2 "${present}" "${expected}" | join -v 2 "${exceptions}" -)
if echo "${missing_files}" | grep -q .; then
  echo "================================="
  echo "Missing files:"
  echo "${missing_files}"
  rc=1
fi

rm "${expected}" "${present}" "${exceptions}"

exit $rc
