FROM perceptilabs.azurecr.io/cuda11.2.2-cudnn8-devel-py38-ubi8

USER 0

RUN yum -y update
RUN yum -y install mesa-libGL

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/lib64:/usr/local/cuda/compat:/usr/local/cuda/targets/x86_64-linux/lib

RUN pip install --upgrade pip

WORKDIR /app
ADD main.py requirements.txt ./
RUN pip install -r requirements.txt

USER 1001
