FROM perceptilabs.azurecr.io/cuda11.2.2-cudnn8-devel-py36-ubi8

USER 0

RUN yum -y update
RUN yum -y install mesa-libGL
RUN yum -y install python3-devel
# Installing python3-devel can undo the link from the base image. Make sure it stays.
RUN ln -sf $(which python3) $(dirname $(which python3))/python

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/lib64:/usr/local/cuda/compat:/usr/local/cuda/targets/x86_64-linux/lib

RUN pip install --upgrade pip

WORKDIR /app
ADD main.py requirements.txt ./
RUN pip install -r requirements.txt

USER 1001
