name: py362_
dependencies:
  - python=3.6.2
  - tensorflow=1.13.1
  - dask[array]=2.1.0
  - psutil=5.6.3
  - scikit-image=0.15.0
  - scipy=1.3.0
  - Cython=0.29.12
  - pycrypto=2.6.1
  - pip:
    - GPUtil==1.4.0
    - gym[atari]
    - sentry-sdk==0.10.2
    - pyinstaller==3.5
    - boto==2.49.0
    - boto3==1.9.233
   
