name: py362_
dependencies:
  - python=3.6.2
  - nomkl=3.0  
  - pip=19.0.3
  - pip:
    - tensorflow-gpu==1.15
    - numpy==1.16.4
    - fsspec==0.6.0
    - pandas==0.25.0
    - dask[array]==2.6.0
    - psutil==5.6.3
    - scikit-image==0.15.0
    - scipy==1.3.0
    - Cython==0.29.14
    - pycrypto==2.6.1
    - GPUtil==1.4.0
    - gym[atari]
    - sentry-sdk==0.10.2
    - pyinstaller==3.5
    - boto==2.49.0
    - boto3==1.9.233
    - azure-storage==0.36.0
    - pylint==2.4.3
    - pytest==5.3.1
    - astor==0.8.0
    
   
