#!/usr/bin/env bash
set -Eeo pipefail

MIGRATIONS_DIR=$(dirname $(dirname $0))
. "${MIGRATIONS_DIR}/common"

install_config(){
  # update the docker-compose file and restart to take the changes
  mydir=$(dirname $0)
  customize_docker_compose_file "${mydir}/docker-compose-after.yml"
  cp "${mydir}/docker-compose-after.yml" "${PL_ROOT_DIR}/docker-compose.yml"
  cp "${mydir}/nginx.conf" "${PL_ROOT_DIR}/nginx.conf"
}

short_circuit(){
  if docker-compose ps --services | grep --quiet fileserver; then
    echo "The fileserver service needs to be removed."
  else
    echo "The fileserver service has already been removed."
    exit 0
  fi
}

main(){
  short_circuit
  install_config
}

[ "${BASH_SOURCE[0]}" != "${0}" ] ||
  main
