#!/usr/bin/env bash
set -euo pipefail

. $(dirname $0)/common

is_perceptilabs_installed(){
  [ -d "${PL_ROOT_DIR}/plabs" ]
}

migrate_one(){
  migration=$1
  description=$(cat system_migrations/${migration}/description.txt)
  echo "Performing system migration $migration : $description"
  system_migrations/${migration}/up
}

run_migrations(){
  if is_perceptilabs_installed; then
    all_migrations=$(ls system_migrations | grep "[[:digit:]]" | sort)
    echo "${all_migrations}" | while read migration; do
      migrate_one $migration
    done
  else
    echo "Performing initial system migration"
    system_migrations/all/up
  fi
}

main(){
  assert_required_variables
  run_migrations
  sudo docker-compose down --remove-orphans
  sudo docker-compose up -d
}

[ "${BASH_SOURCE[0]}" != "${0}" ] ||
  main
