#!/usr/bin/env bash
set -euo pipefail

. $(dirname $0)/common

is_perceptilabs_installed(){
  [ -d "${PL_ROOT_DIR}/plabs" ]
}

run_migrations(){
  if is_perceptilabs_installed; then
    echo "Performing system migration 1: extract db from image"
    system_migrations/000001_extract_db/up
    echo "Performing system migration 2: name the docker network"
    system_migrations/000002_named_network/up
    echo "Performing system migration 3: add keycloak"
    system_migrations/000003_init_kc/up
    echo "Performing system migration 4: add preview kernel"
    system_migrations/000004_preview_kernel/up
  else
    echo "Performing initial system migration"
    system_migrations/all/up
  fi
}

main(){
  assert_required_variables
  run_migrations
  sudo docker-compose down --remove-orphans
  sudo docker-compose up -d
}

[ "${BASH_SOURCE[0]}" != "${0}" ] ||
  main
