version: '3.4'

services:
  db:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - ${PL_ROOT_DIR}/plabsdb:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: rygg
      POSTGRES_USER: rygg
      POSTGRES_PASSWORD: rygg

  rygg:
    image: ${CONTAINER_REGISTRY}/rygg:${PL_VERSION}
    restart: unless-stopped
    environment:
      DJANGO_DATABASE: postgres
      DB_NAME: rygg
      DB_HOST: db
      DB_USER: rygg
      DB_PASS: rygg
    depends_on:
      - db

  frontend:
    image: ${CONTAINER_REGISTRY}/frontend:${PL_VERSION}
    restart: unless-stopped
    depends_on:
      - rygg
      - kernel

  kernel:
    image: ${CONTAINER_REGISTRY}/kernel:${PL_VERSION}
    restart: unless-stopped
    volumes:
      - ${PL_ROOT_DIR}/plabs:/perceptilabs/Documents/Perceptilabs
    environment:
      HOME: /perceptilabs
      PL_FILE_SERVING_TOKEN: thetoken
      PL_TUTORIALS_DATA: /tutorial_data
      PL_FILE_UPLOAD_DIR: /perceptilabs/Documents/Perceptilabs/data
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ${PL_ROOT_DIR}/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rygg
      - kernel
      - frontend
