
parameters:
  - name: start_type
    displayName: How to pick the machine
    type: string
    values:
      - subdomain
      - instance_id
  - name: machine
    displayName: machine (either subdomain or instance_id)
    type: string
  - name: minutes_to_run
    displayName: Minutes to stay running
    default: 60
    type: number
  - name: key
    displayName: SSH key name to add
    type: string
    default: '<none>'

variables:
- name: machine_param
  ${{ if eq( parameters.start_type, 'subdomain') }}:
    value: '-s'
  ${{ if eq( parameters.start_type, 'instance_id') }}:
    value: '-i'
- name: key_param
  ${{ if eq( parameters.key, '<none>') }}:
    value: ''
  ${{ if ne( parameters.key, '<none>') }}:
    value: "-p ${{ parameters.key }}"

steps:

- task: DownloadSecureFile@1
  displayName: Download the ssh key
  name: sshkey
  inputs:
    secureFile: 'azurepipeline.pem'

- task: AWSShellScript@1
  displayName: Run start_machine
  inputs:
    awsCredentials: 'aws'
    regionName: 'us-east-2'
    arguments: ${{ variables['machine_param'] }} "${{ parameters.machine }}" -k "$(sshkey.secureFilePath)" ${{ variables['key_param'] }} -m "${{ parameters.minutes_to_run }}"
    scriptType: 'filePath'
    filePath: 'docker/cd/start_machine'
