
parameters:
  - name: subdomain
    displayName: subdomain
    type: string
  - name: minutes_to_run
    displayName: Minutes to stay running
    default: 60
    type: number
  - name: key
    displayName: SSH key name to add
    type: string
    default: '<none>'


steps:

- task: DownloadSecureFile@1
  displayName: Download the ssh key
  name: sshkey
  inputs:
    secureFile: 'azurepipeline.pem'

- task: AWSShellScript@1
  inputs:
    awsCredentials: 'aws'
    regionName: 'us-east-2'
    arguments: '-s "${{ parameters.subdomain }}" -k "$(sshkey.secureFilePath)" -p "${{ parameters.key }}" -m "${{ parameters.minutes_to_run }}"'
    scriptType: 'filePath'
    filePath: 'docker/cd/start_machine'
    failOnStandardError: true
  condition: ne('${{ parameters.key }}', '<none>')

- task: AWSShellScript@1
  inputs:
    awsCredentials: 'aws'
    regionName: 'us-east-2'
    arguments: '-s "${{ parameters.subdomain }}" -k "$(sshkey.secureFilePath)" -m "${{ parameters.minutes_to_run }}"'
    scriptType: 'filePath'
    filePath: 'docker/cd/start_machine'
    failOnStandardError: true
  condition: eq('${{ parameters.key }}', '<none>')

