---
- hosts: localhost
  tasks:
    - name: Create Keycloak client
      local_action:
        module: keycloak_client
        auth_client_id: admin-cli
        auth_keycloak_url: http://localhost:8080/auth
        auth_realm: master
        auth_username: admin
        auth_password: admin
        client_id: rygg
        state: present
        enabled: True
        redirect_uris:
          - http://localhost:8000/callback/*


