'use strict'
module.exports = {
  NODE_ENV: '"production"',
  HUBSPOT_ID: '"7122301.js"',
  GOOGLE_ANALYTICS_ID: '"UA-114940346-2"',
  FORCE_DEFAULT_PROJECT: '"true"',
  KEYCLOAK_BASE_URL: '"https://keycloak.perceptilabs.com:8443/auth"',
  KEYCLOAK_REALM: '"PerceptiLabs"',
  KEYCLOAK_CLIENT_ID: '"perceptilabs_tool"',
  SENTRY_DSN: '"https://a926ebcbc2a0463ab728fe06ebd750a8@o283802.ingest.sentry.io/6061754"',
  SENTRY_ENABLED: '"false"',
  SENTRY_ENV: '"prod"',  
  GITHUB_CLIENT_ID: '"094271b0edb47c75dc24"',
  ENABLE_LOGROCKET: '"true"',
  LOGROCKET_APP_ID: '"l2mogl/modeling-tool"',
  ENABLE_DATAWIZARD: '"true"',
  INTERCOM_ID: '"ujvkp2qi"',
  USERFLOW_KEY: '"ct_ertrpr7nzfc5himsrvqpz4kota"',
  ENABLE_PUBLIC_DATASET: '"true"',
  ENABLE_SERVING: '"true"',
  ENABLE_FOLDER_LOADING: '"true"',
}
