#!/bin/bash

ROOT_PATH=$(git rev-parse --show-toplevel)
cd ${ROOT_PATH}/rygg
source ${ROOT_PATH}/rygg/.venv/bin/activate
python manage.py migrate
python -m django runserver 0.0.0.0:8000 --settings rygg.settings
