version: '2'

services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rygg
      POSTGRES_USER: rygg
      POSTGRES_PASSWORD: rygg

  rygg:
    image: perceptilabs.azurecr.io/rygg:$PL_IMG_TAG
    environment:
      PL_RYGG_LOG_LEVEL: ERROR
      CORS_WHITELIST: "http://${PL_HOST}:8080"
      DJANGO_DATABASE: postgres
      DB_NAME: rygg
      DB_HOST: db
      DB_USER: rygg
      DB_PASS: rygg
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: perceptilabs.azurecr.io/frontend:$PL_IMG_TAG
    ports:
      - "8080:8080"
    depends_on:
      - rygg
    environment:
      PL_KERNEL_URL: "ws://${PL_HOST}:5000"
      PL_FILESERVER_URL: "http://${PL_HOST}:8011"
      PL_RYGG_URL: "http://${PL_HOST}:8000"
