version: '3.4'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: rygg
      POSTGRES_USER: rygg
      POSTGRES_PASSWORD: rygg

  rygg:
    image: ${CONTAINER_REGISTRY}/rygg:${PL_VERSION}
    environment:
      DJANGO_DATABASE: postgres
      DB_NAME: rygg
      DB_HOST: db
      DB_USER: rygg
      DB_PASS: rygg
    depends_on:
      - db

  frontend:
    image: ${CONTAINER_REGISTRY}/frontend:${PL_VERSION}
    depends_on:
      - rygg
      - kernel

  kernel:
    image: ${CONTAINER_REGISTRY}/kernel:${PL_VERSION}
    volumes:
      - ./plabs:/perceptilabs/Documents/Perceptilabs

    environment:
      HOME: /perceptilabs
      PL_FILE_SERVING_TOKEN: thetoken
      PL_TUTORIALS_DATA: /opt/app-root/src/perceptilabs/tutorial_data

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rygg
      - kernel
      - frontend
