#!/usr/bin/env bash
set -Eeuo pipefail

PL_IMG_TAG=replaceme
REQUIRED_NVIDIA_VERSION=410.129

# Figure out the hostname
read -p "Enter hostname you use to access this computer [${HOSTNAME}] " PL_HOST
if [ -z "${PL_HOST}" ]; then
  PL_HOST=${HOSTNAME}
fi

# plabs will be mounted as the home directory in the kernel
# it has to belong to the docker user
mkdir -p plabs
sudo chown 1001 plabs

echo "Loading docker images"
docker load --quiet --input images.tar

PL_HOST=${PL_HOST} PL_IMG_TAG=${PL_IMG_TAG} docker-compose up -d

which nvidia-smi >/dev/null && nvidia-smi | grep ${REQUIRED_NVIDIA_VERSION} >/dev/null &&
  { GPUS_FLAG=" --gpus all "; echo "using gpu";} ||
  { GPUS_FLAG=""; echo "not using gpu"; }

docker run -it ${GPUS_FLAG} \
  --publish 8011:8011 \
  --publish 5000:5000 \
  --env "CORS_WHITELIST=http://${PL_HOST}:8080" \
  --env "PL_KERNEL_LOG_LEVEL=ERROR" \
  --env "PL_FILESERVER_LOG_LEVEL=ERROR" \
  --env "HOME=/perceptilabs" \
  --env "PL_FILE_SERVING_TOKEN=thetoken" \
  --env "PL_TUTORIALS_DATA=/tutorial_data" \
  --env "LICENSE_NAME=410feb47-7963-4e1f-99eb-5f165168a712" \
  --env "LICENSE_VALUE=gAAAAABf2Ucp_rcI9Ert9pdQ5r5WMmY0Ya3nZPIYTjlTR8UltsbUXxmQQ0-7nuZoSrZr2zUX6pFQyqnGNhBtfepuWN36624Lc9W44eVvU6fzC3IhTeLSbDncGVJUt30N2Djv0607QsIxgfyNCNzvRjKb2zNFZQ-DIdWaIjBKJzCD_yOkjwwYYxvMnFt_5Pqg-2U6qyXCHYmdscBzy3FaC7jFMRt9d_n1ap1fyA7xdkUv8YOkQyzLP3M=" \
  --volume $(pwd)/plabs:/perceptilabs/Documents/Perceptilabs \
  perceptilabs.azurecr.io/kernel:${PL_IMG_TAG}
