apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-sa-role
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: monitor-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: monitor-role
  apiGroup: rbac.authorization.k8s.io
