apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nginx-cache
  name: nginx-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  {{- with .Values.rwo_storage_class }}
  storageClassName: {{ . }}
  {{- end }}
  volumeMode: Filesystem
