apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: redis-data
  name: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  {{- with .Values.rwo_storage_class }}
  storageClassName: {{ . }}
  {{- end }}
  volumeMode: Filesystem
