apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: render
  name: render
spec:
  replicas: 1
  selector:
    matchLabels:
      app: render
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: render
    spec:
      {{- with .Values.imageCredentials.name }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      initContainers:
        - name: make-data-dir
          image: {{ .Values.bash_host.image | quote }}
          command: ['mkdir', '-p', '/plabs/data']
          volumeMounts:
            - name: plabs
              mountPath: /plabs
          imagePullPolicy: {{ .Values.bash_host.pull_policy | default "IfNotPresent" | quote }}
      containers:
        - name: render
          {{- if .Values.render.docker_image_override }}
          image: {{ .Values.render.docker_image_override | quote }}
          {{- else }}
          image: "{{ .Values.render.docker_repo }}:{{ required "pl_docker_tag is a required value" .Values.pl_docker_tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.render.pull_policy | default "IfNotPresent" | quote }}
          args:
            - python
            - main.py
          env:
            - name: container
              value: a
            - name: HOME
              value: /perceptilabs
            - name: PL_KERNEL_CELERY
              value: "1"
            - name: PL_KERNEL_MODE
              value: rendering
            - name: PL_REDIS_URL
              value: redis://{{ .Values.redis_host }}
            - name: PL_RENDER_LOG_LEVEL
              value: {{ .Values.log_level }}
            - name: PL_RYGG_BASE_URL
              value: http://rygg
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - curl --fail localhost:5001/healthy || exit 1
            failureThreshold: 10
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 10
          ports:
            - containerPort: 5001
          resources: {}
          volumeMounts:
            - mountPath: /perceptilabs/Documents/Perceptilabs
              name: plabs
            - mountPath: /opt/app-root/src/queues.yaml
              subPath: queues.yaml
              name: queues-config
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: plabs
          persistentVolumeClaim:
            claimName: plabs
        - name: queues-config
          configMap:
            name: queues-config
            items:
              - key: queues.yaml
                path: queues.yaml
