kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: perceptilabs
  labels:
    app.kubernetes.io/managed-by: Helm
    app: nginx
spec:
  # TODO: this forces us into hard-coding the release name in the keycloak redirect url
  host: "{{ .Release.Namespace }}.{{ required "root_host is a required value" .Values.root_host }}"
  to:
    kind: Service
    name: nginx
    weight: 100
  port:
    targetPort: '80'
  wildcardPolicy: None
